### PR TITLE
WIP to move to a leaner CLI

### PR DESCRIPTION
**Pull request by DarthHater**
The previous CLI was using thor and had some issues with bundler, and we needed to switch to parse the `Gemfile.lock`

This is just shy of a total rewrite, but not 100%. I maintained most of `gems.rb`, and after switching to parsing the `Gemfile.lock`, now I'm seeing the transitive deps come back for the project.

This does:
- Renames to `chelsea` completely
- Maintains mostly the same usage as before
- Trims the deps down BIG TIME
- Adds CircleCI config to have commits run through CI
- Saves Test Results in a format that CircleCI can show us
- Adds LICENSE (set to MIT for now, probs want to switch to Apache long term)

Local run:
```
$ ./chelsea --file Gemfile.lock 
 _____  _            _                   
/  __ \| |          | |                  
| /  \/| |__    ___ | | ___   ___   __ _ 
| |    | '_ \  / _ \| |/ __| / _ \ / _` |
| \__/\| | | ||  __/| |\__ \|  __/| (_| |
 \____/|_| |_| \___||_||___/ \___| \__,_|
                                         
                                         
Version: 0.0.1

[+] Parsing dependencies ...done. Parsed 23 dependencies.
[+] Parsing versions ...done.
[+] Making request to OSS Index server ...done.

Audit Results
=============
[1/23] - pkg:gem/chelsea@0.0.1 No vulnerabilities found!
[2/23] - pkg:gem/diff-lcs@1.3.0 No vulnerabilities found!
[3/23] - pkg:gem/domain_name@0.5.20190701 No vulnerabilities found!
[4/23] - pkg:gem/equatable@0.6.1 No vulnerabilities found!
[5/23] - pkg:gem/http-cookie@1.0.3 No vulnerabilities found!
[6/23] - pkg:gem/mime-types@3.3.1 No vulnerabilities found!
[7/23] - pkg:gem/mime-types-data@3.2019.1009 No vulnerabilities found!
[8/23] - pkg:gem/netrc@0.11.0 No vulnerabilities found!
[9/23] - pkg:gem/pastel@0.7.3 No vulnerabilities found!
[10/23] - pkg:gem/rake@10.5.0 No vulnerabilities found!
[11/23] - pkg:gem/rest-client@2.0.2 No vulnerabilities found!
[12/23] - pkg:gem/rspec@3.9.0 No vulnerabilities found!
[13/23] - pkg:gem/rspec-core@3.9.1 No vulnerabilities found!
[14/23] - pkg:gem/rspec-expectations@3.9.1 No vulnerabilities found!
[15/23] - pkg:gem/rspec-mocks@3.9.1 No vulnerabilities found!
[16/23] - pkg:gem/rspec-support@3.9.2 No vulnerabilities found!
[17/23] - pkg:gem/slop@4.8.0 No vulnerabilities found!
[18/23] - pkg:gem/tty-color@0.5.1 No vulnerabilities found!
[19/23] - pkg:gem/tty-cursor@0.7.1 No vulnerabilities found!
[20/23] - pkg:gem/tty-font@0.5.0 No vulnerabilities found!
[21/23] - pkg:gem/tty-spinner@0.9.3 No vulnerabilities found!
[22/23] - pkg:gem/unf@0.1.4 No vulnerabilities found!
[23/23] - pkg:gem/unf_ext@0.0.7.6 No vulnerabilities found!
```

There's more we could do but this is functional and probably a good stopping point to get this merged into master

### CODE REVIEW

**Comment by DarthHater** [comment]
Got an informal blessing of this from @ken-duck , pushing to master

**Comment by allisterb** [comment]
Hi when I try running an audit on Windows it doesn't seem to get any dependencies from the gemspec:
`chelsea -f .\chelsea.gemspec`
 [+] Parsing dependencies ...done. Parsed 0 dependencies.
No dependencies retrieved. Exiting.

Could @ken-duck or anyone could try the new version on Windows and see if this something peculiar to my Ruby setup.

**Comment by DarthHater** [comment]
@allisterb I need to update the README, but now we are parsing `Gemfile.lock`, as that has the authoritative list of what was installed, etc...

Give that a twirl!

**Comment by allisterb** [comment]
@DarthHater Ohh I see :) sorry didn't fully understand. Tried it on the lock file on Window and everything looks ok.

**Comment by DarthHater** [comment]
Coolio! Yeah that was the big change. I ended up using `bundler`'s utilities to parse it, which made it kinda fun and easy.

**Pull request merged**
